name: EmpViaShapes
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.11
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - optuna
  - plotly
  - scipy
  - tqdm
  - pip
  - ipywidgets
  - scikit-learn
  - seaborn
  - h5py
  - networkx
  - pip:
      - nbdev
      - black
      - wrds
      - kaleido
      - openml
      - ucimlrepo